dist: xenial
language: java
jdk:
  - openjdk10
  - oraclejdk8
  - openjdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
services:
  - xvfb
  - mysql
cache:
  directories:
    - "$HOME/.m2"
before_install:
  - mysql -u root -e "create database videoclubDB";
  - mysql -u root -e "CREATE USER 'spq'@'%' IDENTIFIED BY 'spq'";
  - mysql -u root -e "GRANT ALL ON videoclubDB.* TO 'spq'@'%'";
  - rmiregistry -J-Djava.rmi.server.useCodebaseOnly=false &
